version: '3.7'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/src/.env
    depends_on:
      - db
    volumes:
      - ./backend:/project/
    ports:
      - "5000:5000"

#  frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#    stdin_open: true
#    ports:
#      - "3000:3000"

volumes:
  db-data:
