"""add status system

Revision ID: 2507877b5ded
Revises: 9c9cf724ed12
Create Date: 2022-04-23 15:31:05.460290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2507877b5ded'
down_revision = '9c9cf724ed12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###
